const _ = require('lodash');
const envEs6 = require('./env-es6');
const envNodeFalse = require('./env-node-false');
const defaults = {
    'env': {
        'browser': false,
        'jasmine': false,
        'mocha': false
    },
    'rules': {
        'no-underscore-dangle': 0,
        'no-unexpected-multiline': 1,

        'accessor-pairs': 2,
        'block-scoped-var': 2,
        'curly': 2,
        'dot-notation': 2,
        'eqeqeq': [2, "smart"],
        'guard-for-in': 2,
        'no-alert': 2,
        'no-caller': 2,
        'no-div-regex': 2,
        'no-else-return': 2,
        'no-empty-label': 2,
        'no-eq-null': 0,
        'no-eval': 2,
        'no-extend-native': 0,
        'no-extra-bind': 2,
        'no-fallthrough': 2,
        'no-floating-decimal': 2,
        'no-implied-eval': 2,
        'no-iterator': 2,
        'no-labels': 1,
        'no-lone-blocks': 2,
        'no-loop-func': 2,
        'no-multi-spaces': 0,
        'no-multi-str': 2,
        'no-native-reassign': 2,
        'no-new-func': 2,
        'no-new-wrappers': 2,
        'no-new': 2,
        'no-octal-escape': 2,
        'no-octal': 2,
        'no-param-reassign': 0,
        'no-process-env': 0,
        'no-proto': 2,
        'no-redeclare': 2,
        'no-return-assign': 2,
        'no-script-url': 2,
        'no-self-compare': 2,
        'no-sequences': 2,
        'no-throw-literal': 2,
        'no-unused-expressions': 2,
        'no-void': 2,
        'vars-on-top': 2,
        'wrap-iife': [2, 'inside'],

        'no-catch-shadow': 0,
        'no-delete-var': 2,
        'no-shadow': 2,
        'no-undef-init': 2,
        'no-undef': 2,
        'no-undefined': 2,
        'no-unused-vars': 2,
        'no-use-before-define': 2,

        'brace-style': 2,
        'camelcase': [2, { 'properties': 'always' }],
        'comma-spacing': [2, { 'before': false, 'after': true }],
        'comma-style': [2, 'last'],
        'consistent-this': [2, 'self'],
        'eol-last': 2,
        'func-style': [0, 'declaration'],
        'indent': [2, 4, { 'SwitchCase': 1 }],
        'key-spacing': [2, {
            'beforeColon': false,
            'afterColon': true
        }],
        'max-nested-callbacks': [2, 3],
        'new-cap': 2,
        'new-parens': 2,
        'no-array-constructor': 2,
        'no-lonely-if': 2,
        'no-multiple-empty-lines': [1, { 'max': 2 }],
        'no-nested-ternary': 2,
        'object-curly-spacing': [2, 'always'],
        'no-unneeded-ternary': 2,
        'operator-assignment': [2, 'always'],
        'operator-linebreak': [2, 'after'],
        'padded-blocks': [2, 'never'],
        'quotes': [2, 'single'],
        'semi': [2, 'always'],
        'space-after-keywords': [2, 'always'],
        'space-before-blocks': [2, 'always'],
        'spaced-comment': [2, 'always', { 'exceptions': ['eslint-disable', 'global', 'eslint', 'eslint-env'] }],
        'global-strict': 0,
        'strict': [2, 'function']
    }
};

module.exports = _.merge({}, envEs6, envNodeFalse, defaults);
