'use strict';

module.exports = {
    'extends': [
        './env-es6.js',
        './env-es6-modules-false.js',
        './env-node-false.js'
    ].map(require.resolve),
    'env': {
        'browser': false,
        'jasmine': false,
        'mocha': false
    },
    'rules': {
        'no-underscore-dangle': 'off',
        'no-unexpected-multiline': 'warn',

        'accessor-pairs': 'error',
        'block-scoped-var': 'error',
        'curly': 'error',
        'dot-notation': 'error',
        'eqeqeq': ['error', 'smart'],
        'guard-for-in': 'error',
        'keyword-spacing': 'error',
        'no-alert': 'error',
        'no-caller': 'error',
        'no-div-regex': 'error',
        'no-else-return': 'off',
        'no-eq-null': 'off',
        'no-eval': 'error',
        'no-extend-native': 'off',
        'no-extra-bind': 'error',
        'no-fallthrough': 'error',
        'no-floating-decimal': 'error',
        'no-implied-eval': 'error',
        'no-iterator': 'error',
        'no-labels': 'error',
        'no-lone-blocks': 'error',
        'no-loop-func': 'error',
        'no-multi-spaces': 'off',
        'no-multi-str': 'error',
        'no-native-reassign': 'error',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-new': 'error',
        'no-octal-escape': 'error',
        'no-octal': 'error',
        'no-param-reassign': 'off',
        'no-process-env': 'off',
        'no-proto': 'error',
        'no-redeclare': 'error',
        'no-return-assign': 'error',
        'no-script-url': 'error',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-throw-literal': 'error',
        'no-unused-expressions': 'error',
        'no-void': 'error',
        'vars-on-top': 'off',
        'wrap-iife': ['error', 'inside'],

        'no-catch-shadow': 'off',
        'no-delete-var': 'error',
        'no-shadow': ['error', { 'builtinGlobals': true, 'allow': ['resolve', 'reject', 'cb', 'err'] }],
        'no-undef-init': 'error',
        'no-undef': 'error',
        'no-undefined': 'off',
        'no-unused-vars': 'error',
        'no-use-before-define': ['error', { 'functions': false }],

        'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
        'camelcase': ['error', { 'properties': 'always' }],
        'comma-spacing': ['error', { 'before': false, 'after': true }],
        'comma-style': ['error', 'last'],
        'consistent-this': ['error', 'self'],
        'eol-last': 'error',
        'func-style': ['off', 'declaration'],
        'indent': ['error', 4, { 'SwitchCase': 1 }],
        'key-spacing': ['error', {
            'beforeColon': false,
            'afterColon': true
        }],
        'max-nested-callbacks': ['error', 3],
        'new-cap': 'error',
        'new-parens': 'error',
        'no-array-constructor': 'error',
        'no-lonely-if': 'error',
        'no-multiple-empty-lines': ['warn', { 'max': 2 }],
        'no-nested-ternary': 'error',
        'object-curly-spacing': ['error', 'always'],
        'no-unneeded-ternary': 'error',
        'operator-assignment': ['error', 'always'],
        'operator-linebreak': ['error', 'after'],
        'padded-blocks': ['error', 'never'],
        'quotes': ['error', 'single', { 'avoidEscape': true }],
        'semi': ['error', 'always'],
        'space-before-blocks': ['error', 'always'],
        'spaced-comment': ['error', 'always', { 'exceptions': ['eslint-disable', 'global', 'eslint', 'eslint-env'] }],
        'global-strict': 'off',
        'strict': ['error', 'safe'],

        // new
        'array-bracket-spacing': 'error',
        'array-callback-return': 'error',
        'arrow-body-style': ['error', 'as-needed'],
        'arrow-spacing': 'error',
        'block-spacing': 'error',
        'comma-dangle': ['error', 'always-multiline'],
        'computed-property-spacing': 'error',
        'max-depth': ['error'],
        'max-len': ['error', { 'code': 140, 'ignoreTrailingComments': true, 'ignoreUrls': true }],
        'max-params': ['error', 5],
        'newline-per-chained-call': 'error',
        'no-case-declarations': 'error',
        'no-class-assign': 'error',
        'no-cond-assign': ['error', 'always'],
        'no-confusing-arrow': ['error', { 'allowParens': true }],
        'no-console': 'error',
        'no-debugger': 'error',
        'no-duplicate-imports': 'error',
        'no-negated-condition': 'error',
        'no-negated-in-lhs': 'error',
        'no-shadow-restricted-names': 'error',
        'no-spaced-func': 'error',
        'no-trailing-spaces': 'error',
        'no-useless-call': 'error',
        'no-useless-escape': 'error',
        'one-var': ['error', 'never'],
        'prefer-const': 'error',
        'prefer-spread': 'error',
        'prefer-template': 'error',
        'quote-props': ['error', 'consistent-as-needed'],
        'space-before-function-paren': 'error',
        'space-infix-ops': 'error',
        'space-unary-ops': 'error',
        'template-curly-spacing': 'error',
        'yoda': 'error'
    }
};
